import test from 'node:test';
import assert from 'node:assert/strict';
import {tick,stepBots,publicState,blocked,act,reset,HOUSES} from '../worker/rules.js';
function room(n=1){return{autofill:true,phase:'waiting',seq:0,events:[],marks:[[],[],[],[]],players:Array.from({length:4},(_,i)=>i<n?{token:'live-'+i,name:'Person '+i,connected:true,lastSeen:10000,lastMove:10000,x:350+i*34,y:885,ready:false,lastFart:0,lastClean:0}:null)};}
function start(s,now=10000){for(let i=0;i<s.players.length;i++)if(s.players[i]&&!s.players[i].bot)tick(s,i,{ready:true},now);}
test('autofill starts solo with three ready bots and keeps human identities',()=>{const s=room();const human=s.players[0];start(s);assert.equal(s.phase,'playing');assert.equal(s.players[0],human);assert.equal(s.players.filter(p=>p.bot).length,3);assert.ok(s.players.slice(1).every(p=>p.ready&&p.token===null));assert.equal(publicState(s,20000).players[1].online,true);assert.equal(publicState(s,10000).players[1].bot,true);});
test('autofill waits for every joined person and does not replace an offline seat',()=>{const s=room(2);tick(s,0,{ready:true},10000);assert.equal(s.phase,'waiting');assert.equal(s.players.filter(Boolean).length,2);s.players[1].connected=false;tick(s,1,{ready:true},10000);assert.equal(s.phase,'waiting');assert.equal(s.players.filter(Boolean).length,2);s.players[1].connected=true;tick(s,1,{ready:true},10000);assert.equal(s.phase,'playing');assert.equal(s.players.filter(p=>p.bot).length,2);assert.equal(s.players[1].name,'Person 1');});
test('four live players start unchanged with autofill enabled',()=>{const s=room(4);start(s);assert.equal(s.phase,'playing');assert.equal(s.players.filter(p=>p.bot).length,0);});
test('bots navigate around homes, tag opponents, emit mega farts and finish a round',()=>{const s=room();start(s);for(let now=10200;now<150000&&s.phase==='playing';now+=200){s.players[0].lastSeen=now;stepBots(s,now);for(const p of s.players)assert.ok(!blocked(p.x,p.y),'bots stay outside house walls');}assert.equal(s.phase,'finished');assert.ok(s.winner>0);assert.equal(s.marks[s.winner].length,0);assert.ok(s.marks.every((m,i)=>i===s.winner||m.includes(s.winner)));assert.equal(s.series.wins[s.winner],1);});
test('bots respect hit slowdown and pause when a live player disconnects',()=>{const normal=room(),slow=room();start(normal);start(slow);normal.players[1].x=slow.players[1].x=300;slow.players[1].slowedUntil=13000;stepBots(normal,10200);stepBots(slow,10200);const distance=s=>Math.hypot(s.players[1].x-300,s.players[1].y-885);assert.ok(Math.abs(distance(slow)*2-distance(normal))<.01);const before=structuredClone(slow.players[1]);slow.players[0].connected=false;assert.equal(stepBots(slow,10400),false);assert.deepEqual(slow.players[1],before);assert.equal(publicState(slow,10400).paused,true);});
test('bots cleanse only their home and wait for full mega charge before firing',()=>{const s=room();start(s);s.marks=[[2],[0],[0],[0]];stepBots(s,10200);assert.deepEqual(s.marks[0],[2]);assert.deepEqual(s.marks[1],[]);const p=s.players[2];p.x=HOUSES[3].x+100;p.y=HOUSES[3].y+227;p.fartReadyAt=0;p.chargeStarted=null;stepBots(s,10400);assert.equal(p.chargeStarted,10400);stepBots(s,11000);assert.equal(p.chargeStarted,10400);stepBots(s,11600);assert.equal(p.chargeStarted,null);assert.ok(s.events.some(e=>e.actor===2&&e.kind==='fart'&&e.mega));assert.equal(p.fartReadyAt,14100);});
test('bots persist across rematches but wait for the human before moving',()=>{const s=room();start(s);s.marks=[[],[0],[0],[0]];act(s,0,'clean',10000);assert.equal(s.phase,'finished');act(s,0,'rematch',11000);assert.equal(s.phase,'waiting');assert.ok(s.players.slice(1).every(p=>p.ready&&p.bot));assert.equal(s.players[0].ready,false);const before=structuredClone(s.players);stepBots(s,12000);assert.deepEqual(s.players,before);tick(s,0,{ready:true},12000);assert.equal(s.phase,'playing');assert.equal(s.series.round,2);reset(s);assert.equal(s.phase,'waiting');});
