import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const houses=[{x:75,y:155},{x:525,y:155},{x:75,y:610},{x:525,y:610}],colors=['#ff4fca','#42fff0','#ffd05a','#9f8aff'];
function view(width,height){const draws=[],shaders=[];let vp,fogOffset;const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:()=>0,shaderSource:(_shader,src)=>shaders.push(src),uniform1f:(_loc,value)=>fogOffset=value,uniformMatrix4fv:(_loc,_transpose,m)=>vp=m,bufferData:(_target,data)=>{assert.equal(data.length%11,0);assert.ok(data.every(Number.isFinite));draws.push(data.length/11);}},{get:(o,k)=>o[k]||(()=>{})});const labels=[];const labelCtx=new Proxy({fillText:s=>labels.push(s)},{get:(o,k)=>o[k]||(()=>{})});const canvas={width,height,getContext:type=>type==='webgl'?gl:null,getBoundingClientRect:()=>({width,height,left:0,top:0})},labelCanvas={getContext:()=>labelCtx};let labelResizes=0;for(const key of ['width','height']){let value;Object.defineProperty(labelCanvas,key,{get:()=>value,set:next=>{value=next;labelResizes++;}});}const env={devicePixelRatio:1};vm.createContext(env);vm.runInContext(fs.readFileSync('public/city3d.js','utf8'),env);const city=env.createCityRenderer(canvas,labelCanvas,houses,colors);return{city,draws,labels,getVP:()=>vp,getFogOffset:()=>fogOffset,shaders,getLabelResizes:()=>labelResizes};}
const players=colors.map((_,slot)=>({slot,name:['Alex','Sam','Jordan','Casey'][slot],x:350+slot*34,y:885,slowedUntil:0,chargeStarted:null}));
test('3D renderer has finite geometry and clickable doorsteps on portrait and desktop views',()=>{for(const [width,height] of [[390,550],[1000,600]]){const v=view(width,height);v.city.render({players,marks:[[],[],[],[]],particles:[],now:10000,slot:2});assert.ok(v.draws[0]>1000);assert.ok(v.labels.includes('Jordan · YOU'));for(const h of houses){const x=h.x+100,y=h.y+227,wx=(x-400)/28,wz=(y-490)/28,m=v.getVP(),clip=[0,0,0,0];for(let r=0;r<4;r++)clip[r]=m[r]*wx+m[8+r]*wz+m[12+r];const sx=(clip[0]/clip[3]+1)*width/2,sy=(1-clip[1]/clip[3])*height/2;assert.ok(sx>=0&&sx<=width&&sy>=0&&sy<=height,'doorstep is on screen');const p=v.city.pick(sx,sy);assert.ok(Math.abs(p.x-x)<.01&&Math.abs(p.y-y)<.01,'tap projects back onto gameplay target');}}});
test('tags add whole-home gas, slowdowns add pulsing glow, and cleansing adds a cyan particle pass',()=>{const v=view(390,550);v.city.render({players,marks:[[],[],[],[]],particles:[],now:10000,slot:0});const normal=v.draws.slice();v.draws.length=0;v.city.render({players:players.map(p=>({...p,slowedUntil:11500,chargeStarted:9500})),marks:[[1],[0],[],[]],particles:[{x:175,y:382,height:1,r:20,t:3,max:3,clean:true}],now:10000,slot:0});assert.ok(v.draws[0]>normal[0],'charge rings are drawn');assert.ok(v.draws[2]>normal[2],'slowed players have glow geometry');assert.ok(v.draws[3]>normal[3],'house gas and cleansing cloud are drawn');});
test('renderer returns a fallback signal when WebGL is unavailable',()=>{const env={};vm.createContext(env);vm.runInContext(fs.readFileSync('public/city3d.js','utf8'),env);assert.equal(env.createCityRenderer({getContext:()=>null},{},houses,colors),null);});

test('labels stay stable across frames and hit glow clears after slowdown',()=>{const v=view(390,844),state={players:players.map(p=>({...p,slowedUntil:11500})),marks:[[],[],[],[]],particles:[],now:10000,slot:0};v.city.render(state);assert.equal(v.getLabelResizes(),2);assert.ok(v.labels.includes('Alex · HOME'));assert.ok(v.labels.every(s=>!s.includes('undefined')&&!s.includes('null')));const glow=v.draws[2];v.draws.length=0;v.city.render({...state,now:12000});assert.equal(v.getLabelResizes(),2,'same-size frames do not reset the text canvas');assert.ok(v.draws[2]<glow,'expired hits remove slowdown glow');});

test('portrait camera fit preserves prototype fog brightness for homes, players and gas',()=>{
const desktop=view(1000,600),portrait=view(390,844),state={players,marks:[[1],[],[],[]],particles:[],now:10000,slot:0};desktop.city.render(state);portrait.city.render(state);
assert.equal(desktop.getFogOffset(),0);assert.ok(portrait.getFogOffset()>50);
assert.ok(portrait.shaders.some(src=>src.includes('dist=gl_Position.w-fogOffset;')),'shader uses camera compensation');
for(const [x,y,z] of [[-8,3,-9],[8,3,8],[0,2,14],[-8,5,-9]]){
const fog=v=>{const m=v.getVP(),depth=m[3]*x+m[7]*y+m[11]*z+m[15]-v.getFogOffset();return Math.max(0,Math.min(.65,(depth-28)/65));};
assert.ok(Math.abs(fog(desktop)-fog(portrait))<.000001,'same subject keeps the same brightness in portrait');
}
});
