import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {act,tick,publicState,HOUSES,movePlayer} from '../worker/rules.js';
function state(){return {code:'ABC234',phase:'playing',winner:null,seq:0,events:[],marks:[[],[],[],[]],players:Array.from({length:4},(_,i)=>({token:'t'+i,device:'d'+i,x:350+i*35,y:885,lastSeen:10000,lastMove:10000,lastFart:0,lastClean:0,ready:true,points:0}))};}
function doorstep(s,slot,house){s.players[slot].x=HOUSES[house].x+100;s.players[slot].y=HOUSES[house].y+227;}
test('one player cannot start; two, three and four players can start only when all joined players are ready',()=>{for(const count of [1,2,3,4]){const s=state();s.phase='waiting';s.players=s.players.map((p,i)=>i<count?p:null);s.players[0].ready=false;tick(s,0,{},10000);assert.equal(s.phase,'waiting');tick(s,0,{ready:true},10000);assert.equal(s.phase,count>=2?'playing':'waiting');}});
test('a third unready player blocks two ready players',()=>{const s=state();s.phase='waiting';s.players[3]=null;s.players[2].ready=false;tick(s,0,{},10000);assert.equal(s.phase,'waiting');tick(s,2,{ready:true},10000);assert.equal(s.phase,'playing');});
test('two-player farts and rematch safely skip empty seats',()=>{const s=state();s.players[2]=s.players[3]=null;act(s,0,'fart',10000);assert.equal(s.events.at(-1).victims.length,1);assert.equal(publicState(s,10000).players[0].points,undefined);for(let i=1;i<4;i++){doorstep(s,0,i);act(s,0,'fart',11100+i*1100);}assert.equal(s.winner,0);act(s,1,'rematch',15500);assert.equal(s.phase,'waiting');assert.equal(s.players.filter(Boolean).length,2);});
test('offline player prevents start and pauses active actions',()=>{const s=state();s.players[3].lastSeen=0;s.phase='waiting';tick(s,0,{},10000);assert.equal(s.phase,'waiting');s.phase='playing';assert.throws(()=>act(s,0,'fart',10000),/reconnect/);assert.equal(s.events.length,0);});
test('fart anywhere, proximity player slowdowns, house marks, cooldown',()=>{const s=state();act(s,0,'fart',10000);assert.equal(s.events.at(-1).kind,'fart');assert.equal(s.events.at(-1).victims.length,1);assert.equal(publicState(s,10000).players[0].points,undefined);assert.deepEqual(s.marks,[[],[],[],[]]);assert.throws(()=>act(s,0,'fart',10500),/recharging/);doorstep(s,0,0);act(s,0,'fart',11100);assert.deepEqual(s.marks[0],[0]);act(s,0,'fart',12200);assert.deepEqual(s.marks[0],[0]);});
test('cleanse requires the own doorstep, affects only that home, and emits there',()=>{const s=state();s.marks[0]=[1,2];s.marks[1]=[0,1,2,3];doorstep(s,0,1);assert.throws(()=>act(s,0,'clean',10000),/own front door/);assert.deepEqual(s.marks[0],[1,2]);assert.equal(s.events.length,0);doorstep(s,0,0);act(s,0,'clean',10000);assert.deepEqual(s.marks[0],[]);assert.deepEqual(s.marks[1],[0,1,2,3]);assert.equal(s.events.at(-1).house,0);assert.equal(s.events.at(-1).x,HOUSES[0].x+100);assert.equal(s.events.at(-1).y,HOUSES[0].y+227);assert.throws(()=>act(s,0,'clean',11000),/recharging/);s.players[1].x=400;s.players[1].y=885;assert.throws(()=>act(s,1,'clean',10000),/own front door/);doorstep(s,1,1);act(s,1,'clean',10000);assert.deepEqual(s.marks[1],[]);assert.equal(publicState(s,10000).players[0].progress,0);});
test('winning requires three opponent houses and a clean home, rematch clears round',()=>{const s=state();for(let i=1;i<4;i++){doorstep(s,0,i);act(s,0,'fart',10000+(i-1)*1100);}assert.equal(s.phase,'finished');assert.equal(s.winner,0);act(s,2,'rematch',14500);assert.equal(s.phase,'waiting');assert.equal(s.winner,null);assert.ok(s.players.every(p=>!p.ready&&p.points===undefined));assert.ok(s.marks.every(m=>m.length===0));});
test('movement blocks buildings, bounds speed, and ignores invalid coordinates',()=>{const p=state().players[0];p.x=175;p.y=390;movePlayer(p,{x:175,y:100},10100,true);assert.ok(p.y>=390-40);movePlayer(p,{x:Infinity,y:4},10200,true);assert.ok(Number.isFinite(p.x));p.x=HOUSES[0].x+100;p.y=HOUSES[0].y+208;const edge=p.y;movePlayer(p,{x:p.x,y:HOUSES[0].y+100},11000,true);assert.ok(p.y>=edge);});

test('dirty home blocks victory until cleansed; own-house tags do not count toward progress',()=>{for(const mark of [0,1]){const s=state();s.marks[0]=[mark];for(let i=1;i<4;i++){doorstep(s,0,i);act(s,0,'fart',10000+(i-1)*1100);}assert.equal(s.phase,'playing');assert.equal(s.winner,null);assert.equal(publicState(s,12200).players[0].progress,3);assert.equal(publicState(s,12200).players[0].homeClean,false);doorstep(s,0,0);act(s,0,'clean',13300);assert.equal(s.winner,0);assert.equal(s.events.at(-1).kind,'win');assert.equal(publicState(s,13300).players[0].homeClean,true);}});
test('cleansing before all three opponent houses are tagged does not win',()=>{const s=state();s.marks=[[1],[0],[0],[]];doorstep(s,0,0);act(s,0,'clean',10000);assert.equal(s.phase,'playing');doorstep(s,0,3);act(s,0,'fart',11100);assert.equal(s.winner,0);});

