import test from 'node:test';import assert from 'node:assert/strict';import {NeonRoom} from '../worker/room.js';
function setup(){const data=new Map(),sockets=[];let alarm=null;const ctx={storage:{async get(k){return structuredClone(data.get(k));},async put(k,v){data.set(k,structuredClone(v));},async delete(k){data.delete(k);},async getAlarm(){return alarm;},async setAlarm(v){alarm=v;}},blockConcurrencyWhile(fn){this.loaded=fn();},getWebSockets(){return sockets.filter(s=>!s.closed);},acceptWebSocket(ws){sockets.push(ws);}};return{ctx,sockets,room:new NeonRoom(ctx,{})};}
function ws(){return{attachment:null,messages:[],closed:false,serializeAttachment(a){this.attachment=a;},deserializeAttachment(){return this.attachment;},send(m){this.messages.push(JSON.parse(m));},close(){this.closed=true;}};}
async function http(room,path,b){const r=await room.fetch(new Request('https://test.invalid/api/'+path,{method:'POST',body:JSON.stringify({code:'ABC234',...b})}));return{status:r.status,...await r.json()};}
async function crew(n=2){const h=setup();await h.ctx.loaded;const clients=[];for(let i=0;i<n;i++){const joined=await http(h.room,i?'join':'create',{slot:i,device:'device-'+i});assert.equal(joined.status,200);const s=ws();h.sockets.push(s);s.serializeAttachment({authenticated:false,openedAt:Date.now()});await h.room.webSocketMessage(s,JSON.stringify({type:'hello',token:joined.token}));clients.push({ws:s,token:joined.token,slot:i});}return{...h,clients};}
async function message(h,i,data){await h.room.webSocketMessage(h.clients[i].ws,JSON.stringify(data));return h.clients[i].ws.messages.at(-1);}
test('socket ready persists and all joined players must acknowledge ready',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});assert.equal(h.room.room.phase,'waiting');await message(h,1,{type:'ready',id:'r1',ready:true});assert.equal(h.room.room.phase,'playing');assert.equal(h.clients[1].ws.messages.at(-1).type,'ack');});
test('command IDs prevent replayed farts from counting twice',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,1,{type:'ready',id:'r1',ready:true});await message(h,0,{type:'action',kind:'fart',id:'fart1'});assert.equal(h.room.room.events.filter(e=>e.kind==='fart').length,1);await message(h,0,{type:'action',kind:'fart',id:'fart1'});assert.equal(h.room.room.events.filter(e=>e.kind==='fart').length,1);});
test('only host restarts; restart returns to lobby with readiness cleared',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,1,{type:'ready',id:'r1',ready:true});const denied=await message(h,1,{type:'action',kind:'restart',id:'bad'});assert.equal(denied.status,403);await message(h,0,{type:'action',kind:'restart',id:'restart'});assert.equal(h.room.room.phase,'waiting');assert.ok(h.room.room.players.filter(Boolean).every(p=>!p.ready));});
test('disconnect pauses, host removes stale player, removed token cannot reconnect',async()=>{const h=await crew(3);for(let i=0;i<3;i++)await message(h,i,{type:'ready',id:'r'+i,ready:true});h.clients[2].ws.closed=true;await h.room.webSocketClose(h.clients[2].ws);assert.equal(h.room.state(0).state.paused,true);await message(h,0,{type:'action',kind:'remove',target:2,id:'tooSoon'});assert.ok(h.room.room.players[2]);h.room.room.players[2].disconnectedAt=Date.now()-11000;await message(h,0,{type:'action',kind:'remove',target:2,id:'remove'});assert.equal(h.room.room.players[2],null);assert.equal(h.room.state(0).state.paused,false);const newcomer=ws();h.sockets.push(newcomer);await h.room.webSocketMessage(newcomer,JSON.stringify({type:'hello',token:h.clients[2].token}));assert.equal(newcomer.messages.at(-1).status,401);});
test('host transfers after disconnect grace and two-player recovery returns lone player to lobby',async()=>{const h=await crew();h.clients[0].ws.closed=true;await h.room.webSocketClose(h.clients[0].ws);h.room.room.players[0].disconnectedAt=Date.now()-21000;await message(h,1,{type:'heartbeat'});assert.equal(h.room.room.hostSlot,1);await message(h,1,{type:'action',kind:'remove',target:0,id:'remove'});assert.equal(h.room.room.phase,'waiting');assert.equal(h.room.room.players.filter(Boolean).length,1);});
test('authenticated state is recoverable after room recreation',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'ready',ready:true});const restored=new NeonRoom(h.ctx,{});await h.ctx.loaded;assert.equal(restored.room.players[0].ready,true);assert.equal(restored.sockets().length,2);});
test('pending alarms are not postponed by frequent movement',async()=>{const h=await crew();const first=await h.ctx.storage.getAlarm();await h.room.arm();assert.equal(await h.ctx.storage.getAlarm(),first);});


test('charged actions and series scores survive storage and reset for next round',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,1,{type:'ready',id:'r1',ready:true});const start=await message(h,0,{type:'action',kind:'charge',id:'charge1'});assert.equal(start.type,'ack');h.room.room.players[0].chargeStarted=Date.now()-1100;const fired=await message(h,0,{type:'action',kind:'fart',id:'mega1'});assert.equal(fired.type,'ack');assert.equal(h.room.room.events.at(-1).mega,true);const s=h.room.room;s.marks=[[1],[0],[0],[0]];s.players[0].x=175;s.players[0].y=382;s.players[0].lastMove=Date.now();await message(h,0,{type:'action',kind:'clean',id:'win1'});assert.equal(s.phase,'finished');assert.equal(s.series.wins[0],1);const saved=await h.ctx.storage.get('room');assert.equal(saved.state.series.wins[0],1);await message(h,1,{type:'action',kind:'rematch',id:'next1'});assert.equal(s.series.round,2);assert.equal(s.series.wins[0],1);assert.equal(s.players[0].chargeStarted,null);assert.equal(s.players[1].slowedUntil,0);});

test('custom names validate, normalize, persist and update on waiting-room rejoin',async()=>{const h=setup();await h.ctx.loaded;const bad=await http(h.room,'create',{slot:0,device:'a',name:'   '});assert.equal(bad.status,400);assert.equal(h.room.room,null);const created=await http(h.room,'create',{slot:0,device:'a',name:'  Alex   Rivera  '});assert.equal(created.state.players[0].name,'Alex Rivera');assert.equal(created.state.players[0].points,undefined);const invalid=await http(h.room,'join',{slot:1,device:'b',name:'a'.repeat(17)});assert.equal(invalid.status,400);assert.equal(h.room.room.players[1],null);const joined=await http(h.room,'join',{slot:1,device:'b',name:'Sam'});assert.equal(joined.state.players[1].name,'Sam');const rejoined=await http(h.room,'join',{slot:0,device:'a',name:'Ace'});assert.equal(rejoined.state.players[0].name,'Ace');const saved=await h.ctx.storage.get('room');assert.equal(saved.state.players[0].name,'Ace');});

test('host autofill is persisted, idempotent and fills only empty seats on ready',async()=>{const h=await crew(2);const denied=await message(h,1,{type:'autofill',id:'deny',enabled:true});assert.equal(denied.status,403);const enabled=await message(h,0,{type:'autofill',id:'fill',enabled:true});assert.equal(enabled.type,'ack');assert.equal(h.room.room.autofill,true);assert.equal(h.room.room.players.filter(Boolean).length,2);await message(h,0,{type:'autofill',id:'fill',enabled:true});await message(h,0,{type:'ready',id:'r0',ready:true});assert.equal(h.room.room.phase,'waiting');await message(h,1,{type:'ready',id:'r1',ready:true});assert.equal(h.room.room.phase,'playing');assert.ok(h.room.room.players[2].bot);assert.equal(h.room.room.players[1].token,h.clients[1].token);h.room.refresh(Date.now());assert.equal(h.room.state(0).state.paused,false);assert.ok((await h.ctx.storage.getAlarm())<=Date.now()+250);const saved=await h.ctx.storage.get('room');assert.equal(saved.state.players[2].bot,true);const activeDenied=await message(h,0,{type:'autofill',id:'late',enabled:false});assert.equal(activeDenied.type,'error');});
test('solo bot room stays human-hosted, permits bot replacement in lobby, and empties on last human leaving',async()=>{const h=await crew(1);await message(h,0,{type:'autofill',id:'fill',enabled:true});await message(h,0,{type:'ready',id:'r0',ready:true});assert.equal(h.room.room.phase,'playing');await message(h,0,{type:'action',kind:'restart',id:'reset'});const joined=await http(h.room,'join',{slot:2,device:'new-person',name:'Taylor'});assert.equal(joined.status,200);assert.ok(!h.room.room.players[2].bot);assert.equal(h.room.room.players[2].name,'Taylor');await http(h.room,'leave',{token:joined.token});await http(h.room,'leave',{token:h.clients[0].token});assert.equal(h.room.room.players.filter(Boolean).length,0);assert.equal(h.room.room.phase,'waiting');});
test('bot state restores and alarm advances bots without making them host or accepting bot credentials',async()=>{const h=await crew(1);await message(h,0,{type:'autofill',id:'fill',enabled:true});await message(h,0,{type:'ready',id:'r0',ready:true});const restored=new NeonRoom(h.ctx,{});await h.ctx.loaded;assert.ok(restored.room.players[1].bot);restored.room.lastBotTick=Date.now()-200;const before=restored.room.players[1].x;await restored.alarm();assert.notEqual(restored.room.players[1].x,before);assert.equal(restored.room.hostSlot,0);const intruder=ws();h.sockets.push(intruder);await restored.webSocketMessage(intruder,JSON.stringify({type:'hello',token:null}));assert.equal(intruder.messages.at(-1).status,401);h.clients[0].ws.closed=true;restored.room.players[0].connected=false;restored.room.players[0].disconnectedAt=Date.now()-30000;restored.refresh(Date.now());assert.equal(restored.room.hostSlot,0);assert.equal(restored.state(0).state.paused,true);});
test('turning autofill off removes bots before the round and restores live-only readiness',async()=>{const h=await crew(1);await message(h,0,{type:'autofill',id:'fill',enabled:true});await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,0,{type:'action',kind:'restart',id:'reset'});h.room.room.series.wins[1]=2;await message(h,0,{type:'autofill',id:'off',enabled:false});assert.equal(h.room.room.autofill,false);assert.equal(h.room.room.players.filter(Boolean).length,1);assert.equal(h.room.room.series.wins[1],0);await message(h,0,{type:'ready',id:'r1',ready:true});assert.equal(h.room.room.phase,'waiting');});
test('mega cleanse and its shield persist, command replay cannot extend it, and disconnect cancels charging',async()=>{const h=await crew();for(let i=0;i<2;i++)await message(h,i,{type:'ready',id:'ready'+i,ready:true});const p=h.room.room.players[0];p.x=175;p.y=382;p.lastMove=Date.now();await message(h,0,{type:'action',kind:'chargeClean',id:'chargeClean'});p.cleanChargeStarted=Date.now()-1100;await message(h,0,{type:'action',kind:'clean',id:'cleanMega'});const shield=h.room.room.shieldUntil[0];assert.ok(shield>Date.now());assert.equal(h.room.room.events.at(-1).mega,true);await message(h,0,{type:'action',kind:'clean',id:'cleanMega'});assert.equal(h.room.room.shieldUntil[0],shield);const restored=new NeonRoom(h.ctx,{});await h.ctx.loaded;assert.equal(restored.room.shieldUntil[0],shield);p.cleanChargeStarted=Date.now();h.clients[0].ws.closed=true;await h.room.webSocketClose(h.clients[0].ws);assert.equal(p.cleanChargeStarted,null);});
