import test from 'node:test';import assert from 'node:assert/strict';import {NeonRoom} from '../worker/room.js';
function setup(){const data=new Map(),sockets=[];let alarm=null;const ctx={storage:{async get(k){return structuredClone(data.get(k));},async put(k,v){data.set(k,structuredClone(v));},async delete(k){data.delete(k);},async getAlarm(){return alarm;},async setAlarm(v){alarm=v;}},blockConcurrencyWhile(fn){this.loaded=fn();},getWebSockets(){return sockets.filter(s=>!s.closed);},acceptWebSocket(ws){sockets.push(ws);}};return{ctx,sockets,room:new NeonRoom(ctx,{})};}
function ws(){return{attachment:null,messages:[],closed:false,serializeAttachment(a){this.attachment=a;},deserializeAttachment(){return this.attachment;},send(m){this.messages.push(JSON.parse(m));},close(){this.closed=true;}};}
async function http(room,path,b){const r=await room.fetch(new Request('https://test.invalid/api/'+path,{method:'POST',body:JSON.stringify({code:'ABC234',...b})}));return{status:r.status,...await r.json()};}
async function crew(n=2){const h=setup();await h.ctx.loaded;const clients=[];for(let i=0;i<n;i++){const joined=await http(h.room,i?'join':'create',{slot:i,device:'device-'+i});assert.equal(joined.status,200);const s=ws();h.sockets.push(s);s.serializeAttachment({authenticated:false,openedAt:Date.now()});await h.room.webSocketMessage(s,JSON.stringify({type:'hello',token:joined.token}));clients.push({ws:s,token:joined.token,slot:i});}return{...h,clients};}
async function message(h,i,data){await h.room.webSocketMessage(h.clients[i].ws,JSON.stringify(data));return h.clients[i].ws.messages.at(-1);}
test('socket ready persists and all joined players must acknowledge ready',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});assert.equal(h.room.room.phase,'waiting');await message(h,1,{type:'ready',id:'r1',ready:true});assert.equal(h.room.room.phase,'playing');assert.equal(h.clients[1].ws.messages.at(-1).type,'ack');});
test('command IDs prevent replayed farts from counting twice',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,1,{type:'ready',id:'r1',ready:true});await message(h,0,{type:'action',kind:'fart',id:'fart1'});assert.equal(h.room.room.players[0].points,1);await message(h,0,{type:'action',kind:'fart',id:'fart1'});assert.equal(h.room.room.players[0].points,1);});
test('only host restarts; restart returns to lobby with readiness cleared',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'r0',ready:true});await message(h,1,{type:'ready',id:'r1',ready:true});const denied=await message(h,1,{type:'action',kind:'restart',id:'bad'});assert.equal(denied.status,403);await message(h,0,{type:'action',kind:'restart',id:'restart'});assert.equal(h.room.room.phase,'waiting');assert.ok(h.room.room.players.filter(Boolean).every(p=>!p.ready));});
test('disconnect pauses, host removes stale player, removed token cannot reconnect',async()=>{const h=await crew(3);for(let i=0;i<3;i++)await message(h,i,{type:'ready',id:'r'+i,ready:true});h.clients[2].ws.closed=true;await h.room.webSocketClose(h.clients[2].ws);assert.equal(h.room.state(0).state.paused,true);await message(h,0,{type:'action',kind:'remove',target:2,id:'tooSoon'});assert.ok(h.room.room.players[2]);h.room.room.players[2].disconnectedAt=Date.now()-11000;await message(h,0,{type:'action',kind:'remove',target:2,id:'remove'});assert.equal(h.room.room.players[2],null);assert.equal(h.room.state(0).state.paused,false);const newcomer=ws();h.sockets.push(newcomer);await h.room.webSocketMessage(newcomer,JSON.stringify({type:'hello',token:h.clients[2].token}));assert.equal(newcomer.messages.at(-1).status,401);});
test('host transfers after disconnect grace and two-player recovery returns lone player to lobby',async()=>{const h=await crew();h.clients[0].ws.closed=true;await h.room.webSocketClose(h.clients[0].ws);h.room.room.players[0].disconnectedAt=Date.now()-21000;await message(h,1,{type:'heartbeat'});assert.equal(h.room.room.hostSlot,1);await message(h,1,{type:'action',kind:'remove',target:0,id:'remove'});assert.equal(h.room.room.phase,'waiting');assert.equal(h.room.room.players.filter(Boolean).length,1);});
test('authenticated state is recoverable after room recreation',async()=>{const h=await crew();await message(h,0,{type:'ready',id:'ready',ready:true});const restored=new NeonRoom(h.ctx,{});await h.ctx.loaded;assert.equal(restored.room.players[0].ready,true);assert.equal(restored.sockets().length,2);});
test('pending alarms are not postponed by frequent movement',async()=>{const h=await crew();const first=await h.ctx.storage.getAlarm();await h.room.arm();assert.equal(await h.ctx.storage.getAlarm(),first);});
