import {NAMES,tick,act,publicState} from './rules.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const fail=(message,status=400)=>{const e=new Error(message);e.status=status;throw e;};
export async function api(request,env){try{if(request.method!=='POST')return json({error:'Use POST.'},405);const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)return json({error:'Origin rejected.'},403);if(!env.DB)return json({error:'Multiplayer is temporarily unavailable. Please retry.'},503);const text=await request.text();if(text.length>2500)return json({error:'Request too large.'},413);let b;try{b=JSON.parse(text);}catch{fail('Invalid request.');}const path=new URL(request.url).pathname,now=Date.now(),db=env.DB;const seat=Number(b.slot);if(path==='/api/create'){if(!Number.isInteger(seat)||seat<0||seat>3||typeof b.device!=='string'||b.device.length>100)fail('Choose your house.');for(let i=0;i<5;i++){const bytes=crypto.getRandomValues(new Uint8Array(6)),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',code=Array.from(bytes,x=>alphabet[x%alphabet.length]).join(''),token=crypto.randomUUID();const s={code,phase:'waiting',winner:null,players:[null,null,null,null],marks:[[],[],[],[]],events:[],seq:0};s.players[seat]={token,device:b.device,x:350+seat*34,y:885,ready:false,points:0,lastSeen:now,lastMove:now,lastFart:0,lastClean:0};const r=await db.prepare('INSERT OR IGNORE INTO rooms (code,state,revision,updated_at) VALUES (?,?,0,?)').bind(code,JSON.stringify(s),now).run();if(r.meta.changes)return json({token,slot:seat,state:publicState(s,now)});}fail('Could not make a room. Try again.',503);}
const code=String(b.code||'').toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code))fail('Enter a six-character room code.');for(let attempt=0;attempt<15;attempt++){const row=await db.prepare('SELECT state,revision,updated_at FROM rooms WHERE code=?').bind(code).first();if(!row||now-row.updated_at>86400000)fail('Room not found or expired. Create a new room.',404);const s=JSON.parse(row.state);let slot=s.players.findIndex(p=>p&&p.token===b.token),token=b.token;
if(path==='/api/join'){if(!Number.isInteger(seat)||seat<0||seat>3||typeof b.device!=='string'||b.device.length>100)fail('Choose your house.');const existing=s.players.findIndex(p=>p&&p.device===b.device);if(existing!==-1){slot=existing;token=s.players[slot].token;}else{if(s.phase!=='waiting')fail('This game has already started.');if(s.players[seat])fail(NAMES[seat]+"’s house is already taken. Choose another.",409);token=crypto.randomUUID();slot=seat;s.players[slot]={token,device:b.device,x:350+seat*34,y:885,ready:false,points:0,lastSeen:now,lastMove:now,lastFart:0,lastClean:0};}}
else if(slot===-1)fail('Your seat expired. Rejoin the room.',401);
if(path==='/api/leave'){if(s.phase!=='waiting')fail('You can leave from the lobby.');s.players[slot]=null;}
else if(path==='/api/action'){tick(s,slot,b,now);act(s,slot,b.kind,now);}
else if(path==='/api/sync'||path==='/api/join')tick(s,slot,b,now);
else fail('Unknown endpoint.',404);
const r=await db.prepare('UPDATE rooms SET state=?,revision=revision+1,updated_at=? WHERE code=? AND revision=?').bind(JSON.stringify(s),now,code,row.revision).run();if(r.meta.changes)return json({token,slot,state:publicState(s,now,row.revision+1)});await new Promise(resolve=>setTimeout(resolve,10+Math.random()*30));}return json({error:'Room busy. Please retry.'},503);
}catch(e){if(!e.status&& !['Fart recharging.','Cleanser recharging.','Stand at your own doorstep to cleanse it.','Waiting for all joined players to reconnect.','The match is not playing.','Finish this match first.','Unknown action.'].includes(e.message)){console.error('Multiplayer request failed',e);return json({error:'Connection trouble. Your room is saved; please retry.'},503);}return json({error:e.message},e.status||400);}}
