import {NAMES,ONLINE_MS,online,allOnline,tick,act,reset,publicState} from './rules.js';
const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const roomError=(message,status=400)=>Object.assign(new Error(message),{status});
export class NeonRoom {
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.room=null;this.revision=0;this.lastBroadcast=0;this.dirty=false;this.queue=Promise.resolve();ctx.blockConcurrencyWhile(async()=>{const saved=await ctx.storage.get('room');if(saved){this.room=saved.state;this.revision=saved.revision;} });}
 serial(fn){const task=this.queue.then(fn);this.queue=task.catch(()=>{});return task;}
 async load(code){if(this.room){if(Date.now()-(this.room.updatedAt??Date.now())<86400000)return;this.room=null;await this.ctx.storage.delete('room');}if(this.env.DB){let row;try{row=await this.env.DB.prepare('SELECT state,revision,updated_at FROM rooms WHERE code=?').bind(code).first();}catch(e){if(!String(e.message).includes('no such table'))throw e;}if(row&&Date.now()-row.updated_at<86400000){this.room=JSON.parse(row.state);this.room.updatedAt=row.updated_at;this.room.hostSlot=this.room.players.findIndex(Boolean);this.room.players.forEach(p=>{if(p){p.connected=false;p.disconnectedAt=Date.now();}});this.revision=row.revision;await this.save();}}}
 async save(){if(this.room){await this.ctx.storage.put('room',{state:this.room,revision:this.revision});this.dirty=false;}}
 sockets(slot){return this.ctx.getWebSockets().filter(ws=>{try{const a=ws.deserializeAttachment();return a?.authenticated&&(slot===undefined||a.slot===slot);}catch{return false;}});}
 refresh(now){if(!this.room)return;this.room.players.forEach((p,i)=>{if(!p)return;const attached=this.sockets(i).length>0;if(p.connected&&!attached){p.connected=false;p.disconnectedAt=now;this.dirty=true;}if(p.connected&&now-p.lastSeen>=ONLINE_MS){p.connected=false;p.disconnectedAt??=p.lastSeen+ONLINE_MS;this.dirty=true;}});const s=this.room,host=s.players[s.hostSlot];if(!host||(!online(host,now)&&now-(host.disconnectedAt??host.lastSeen+ONLINE_MS)>=20000)){const next=s.players.findIndex(p=>online(p,now));if(next>=0&&next!==s.hostSlot){s.hostSlot=next;this.dirty=true;}}}
 async arm(){if(this.room){const due=Date.now()+3000,current=await this.ctx.storage.getAlarm();if(current===null||current>due)await this.ctx.storage.setAlarm(due);}}
 state(slot){return{slot,state:publicState(this.room,Date.now(),this.revision)};}
 broadcast(force=false){const now=Date.now();if(!this.room||(!force&&now-this.lastBroadcast<80))return;this.lastBroadcast=now;for(const ws of this.sockets()){const a=ws.deserializeAttachment();if(!this.room.players[a.slot]||this.room.players[a.slot].token!==a.token){try{ws.send(JSON.stringify({type:'removed',error:'Your seat was removed from the room.'}));ws.close(4003,'Seat removed');}catch{}continue;}try{ws.send(JSON.stringify({type:'state',...this.state(a.slot)}));}catch{}}}
 newPlayer(slot,device,now){return{token:crypto.randomUUID(),device,x:350+slot*34,y:885,ready:false,points:0,lastSeen:now,lastMove:now,lastFart:0,lastClean:0,connected:false,disconnectedAt:now,commands:[]};}
 validateSeat(b){if(!Number.isInteger(b.slot)||b.slot<0||b.slot>3||typeof b.device!=='string'||!b.device||b.device.length>100)throw roomError('Choose your house.');}
 recover(slot,b,now){const s=this.room;this.refresh(now);if(slot!==s.hostSlot)throw roomError('Only the room host can manage the match.',403);if(b.kind==='restart'){reset(s);return;}if(b.kind==='remove'){const target=b.target;if(!Number.isInteger(target)||target<0||target>3||target===slot||!s.players[target])throw roomError('Choose a disconnected player.');const p=s.players[target];if(online(p,now)||now-(p.disconnectedAt??p.lastSeen+ONLINE_MS)<10000)throw roomError('Give that player 10 seconds to reconnect first.');s.players[target]=null;s.marks=s.marks.map(m=>m.filter(x=>x!==target));if(s.players.filter(Boolean).length<2)reset(s);return;}throw roomError('Unknown room control.');}
 async fetch(request){return this.serial(async()=>{try{const b=request.method==='POST'?await request.json():{code:new URL(request.url).searchParams.get('code')};if(!/^[A-Z2-9]{6}$/.test(b.code||''))throw roomError('Enter a six-character room code.');await this.load(b.code);const path=new URL(request.url).pathname,now=Date.now();if(path==='/api/create'){this.validateSeat(b);if(this.room)throw roomError('Room code already exists.',409);this.room={code:b.code,updatedAt:now,hostSlot:b.slot,phase:'waiting',winner:null,players:[null,null,null,null],marks:[[],[],[],[]],events:[],seq:0};this.room.players[b.slot]=this.newPlayer(b.slot,b.device,now);this.revision++;await this.save();await this.arm();return reply({token:this.room.players[b.slot].token,...this.state(b.slot)});}
if(!this.room)throw roomError('Room not found or expired. Create a new room.',404);this.refresh(now);
if(path==='/socket'){if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return reply({error:'WebSocket upgrade required.'},426);const pair=new WebSocketPair();const [client,server]=Object.values(pair);server.serializeAttachment({authenticated:false,openedAt:now});this.ctx.acceptWebSocket(server);await this.arm();return new Response(null,{status:101,webSocket:client});}
let slot=this.room.players.findIndex(p=>p?.token===b.token),token=b.token;
if(path==='/api/join'){this.validateSeat(b);const existing=this.room.players.findIndex(p=>p?.device===b.device);if(existing>=0){slot=existing;token=this.room.players[slot].token;}else{if(this.room.phase!=='waiting')throw roomError('This game has already started.');if(this.room.players[b.slot])throw roomError(NAMES[b.slot]+"’s house is already taken. Choose another.",409);slot=b.slot;this.room.players[slot]=this.newPlayer(slot,b.device,now);token=this.room.players[slot].token;}}
else{if(slot<0)throw roomError('Your seat expired. Rejoin the room.',401);if(path==='/api/leave'){this.room.players[slot]=null;this.room.marks=this.room.marks.map(m=>m.filter(x=>x!==slot));if(this.room.players.filter(Boolean).length<2)reset(this.room);}else if(path!=='/api/sync')throw roomError('Use the live game connection for actions.',400);}
this.room.updatedAt=now;this.revision++;await this.save();this.broadcast(true);await this.arm();return reply({token,...this.state(slot)});
}catch(e){return reply({error:e.message||'Room unavailable.'},e.status||400);}});}
 async webSocketMessage(ws,message){return this.serial(async()=>{let b;try{if(typeof message!=='string'||message.length>2500)throw roomError('Invalid game message.');b=JSON.parse(message);const a=ws.deserializeAttachment(),s=this.room,now=Date.now();if(!s)throw roomError('Room expired.',404);if(!a?.authenticated){if(b.type!=='hello')throw roomError('Join the room first.',401);const slot=s.players.findIndex(p=>p?.token===b.token);if(slot<0)throw roomError('Your seat expired. Rejoin the room.',401);for(const old of this.sockets(slot)){if(old!==ws){old.serializeAttachment({authenticated:false,replaced:true,openedAt:now});try{old.close(4001,'Connected from another tab');}catch{}}}ws.serializeAttachment({authenticated:true,slot,token:b.token});s.players[slot].connected=true;s.players[slot].lastSeen=now;s.players[slot].disconnectedAt=null;s.players[slot].lastMove=now;this.revision++;await this.save();this.broadcast(true);await this.arm();return;}
const p=s.players[a.slot];if(!p||p.token!==a.token)throw roomError('Your seat was removed.',401);p.connected=true;p.lastSeen=now;p.disconnectedAt=null;this.refresh(now);
if(b.type==='ready'||b.type==='action'){if(typeof b.id!=='string'||b.id.length>80)throw roomError('Invalid action ID.');p.commands??=[];if(p.commands.includes(b.id)){ws.send(JSON.stringify({type:'ack',id:b.id,...this.state(a.slot)}));return;}}
if(b.type==='ready'){if(s.phase!=='waiting')throw roomError('The match has already started.');if(typeof b.ready!=='boolean')throw roomError('Choose ready or not ready.');tick(s,a.slot,{ready:b.ready},now);}
else if(b.type==='action'){tick(s,a.slot,{position:b.position},now);if(['restart','remove'].includes(b.kind))this.recover(a.slot,b,now);else act(s,a.slot,b.kind,now);}
else if(b.type==='move'||b.type==='heartbeat'){tick(s,a.slot,{position:b.position},now);}
else throw roomError('Unknown game message.');
if(b.id){p.commands.push(b.id);p.commands=p.commands.slice(-32);}s.updatedAt=now;this.revision++;this.dirty=true;const important=b.type==='ready'||b.type==='action';if(important)await this.save();this.broadcast(important);if(b.id)ws.send(JSON.stringify({type:'ack',id:b.id,...this.state(a.slot)}));await this.arm();
}catch(e){try{ws.send(JSON.stringify({type:'error',id:b?.id,error:e.message,status:e.status||400}));if(e.status===401||e.status===404)ws.close(4003,'Session ended');}catch{}}});}
 async webSocketClose(ws){return this.serial(async()=>{const a=ws.deserializeAttachment();if(a?.authenticated&&this.room?.players[a.slot]&&!this.sockets(a.slot).some(other=>other!==ws)){const p=this.room.players[a.slot];p.connected=false;p.disconnectedAt=Date.now();this.revision++;await this.save();this.broadcast(true);await this.arm();}});}
 async webSocketError(ws){return this.webSocketClose(ws);}
 async alarm(){return this.serial(async()=>{if(!this.room)return;const now=Date.now();for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment();if(!a?.authenticated&&now-a?.openedAt>10000)try{ws.close(4003,'Authentication timeout');}catch{}}
this.refresh(now);this.revision++;if(this.dirty)await this.save();this.broadcast(true);if(this.sockets().length||this.room.players.some(p=>p&&now-p.lastSeen<60000))await this.arm();});}
}
