export const NAMES=['MATT','NICK','SEAN','MIKE'];
export const HOUSES=[{x:75,y:155},{x:525,y:155},{x:75,y:610},{x:525,y:610}];
export const ONLINE_MS=7000;
export function online(p,now){return !!p&&now-p.lastSeen<ONLINE_MS;}
export function allOnline(s,now){const joined=s.players.filter(Boolean);return joined.length>=2&&joined.every(p=>online(p,now));}
export function blocked(x,y){return HOUSES.some(h=>x>h.x-17&&x<h.x+217&&y>h.y-17&&y<h.y+207);}
export function proximity(p,i){const h=HOUSES[i];return Math.hypot(p.x-h.x-100,p.y-h.y-227)<61;}
export function reset(s){s.phase='waiting';s.winner=null;s.marks=[[],[],[],[]];s.events=[];s.players.forEach((p,i)=>{if(p){p.ready=false;p.points=0;p.x=350+i*34;p.y=885;p.lastFart=0;p.lastClean=0;}});}
export function movePlayer(p,pos,now,allowed){if(!allowed||!pos||!Number.isFinite(pos.x)||!Number.isFinite(pos.y))return;p.lastMove??=now;const dx=pos.x-p.x,dy=pos.y-p.y,d=Math.hypot(dx,dy),max=Math.min(230*Math.max(0,now-p.lastMove)/1000+14,550),ratio=d>max?max/d:1,n=Math.max(1,Math.ceil(d*ratio/10));for(let i=0;i<n;i++){let x=Math.max(25,Math.min(775,p.x+dx*ratio/n)),y=Math.max(25,Math.min(955,p.y+dy*ratio/n));if(!blocked(x,p.y))p.x=x;if(!blocked(p.x,y))p.y=y;}p.lastMove=now;}
export function tick(s,slot,input,now){const p=s.players[slot];p.lastSeen=now;movePlayer(p,input.position,now,s.phase==='playing'&&allOnline(s,now));if(s.phase==='waiting'&&typeof input.ready==='boolean')p.ready=input.ready;if(s.phase==='waiting'&&allOnline(s,now)&&s.players.filter(Boolean).every(p=>p.ready)){s.phase='playing';s.startedAt=now;s.events.push({id:++s.seq,kind:'start',at:now});s.players.forEach(p=>{if(p)p.lastMove=now;});} }
function event(s,e,now){s.events.push({...e,id:++s.seq,at:now});s.events=s.events.filter(e=>now-e.at<12000).slice(-40);}
export function act(s,slot,kind,now){const p=s.players[slot];if(kind==='rematch'){if(s.phase!=='finished')throw Error('Finish this match first.');reset(s);return;}if(s.phase!=='playing')throw Error('The match is not playing.');if(!allOnline(s,now))throw Error('Waiting for all joined players to reconnect.');if(kind==='fart'){if(now-p.lastFart<1000)throw Error('Fart recharging.');p.lastFart=now;const victims=[];s.players.forEach((other,i)=>{if(other&&i!==slot&&Math.hypot(p.x-other.x,p.y-other.y)<65){p.points++;victims.push(i);}});let house=null;for(let i=0;i<4;i++)if(proximity(p,i)){if(!s.marks[i].includes(slot))s.marks[i].push(slot);house=i;}event(s,{kind:'fart',actor:slot,x:p.x,y:p.y,victims,house},now);if(s.marks.every(m=>m.includes(slot))){s.phase='finished';s.winner=slot;event(s,{kind:'win',actor:slot},now);}return;}if(kind==='clean'){if(!proximity(p,slot))throw Error('Stand at your own doorstep to cleanse it.');if(now-p.lastClean<2000)throw Error('Cleanser recharging.');p.lastClean=now;s.marks[slot]=[];event(s,{kind:'clean',actor:slot,house:slot,x:p.x,y:p.y},now);return;}throw Error('Unknown action.');}
export function publicState(s,now,revision=0){return{revision,code:s.code,phase:s.phase,winner:s.winner,marks:s.marks,events:s.events,paused:s.phase==='playing'&&!allOnline(s,now),players:s.players.map((p,i)=>p?{slot:i,name:NAMES[i],x:p.x,y:p.y,ready:p.ready,points:p.points,online:online(p,now),progress:s.marks.filter(m=>m.includes(i)).length}:null)};}
