export const NAMES=['PINK','CYAN','GOLD','PURPLE'];
export const HOUSES=[{x:75,y:155},{x:525,y:155},{x:75,y:610},{x:525,y:610}];
export const ONLINE_MS=7000;
export function online(p,now){return !!p&&(p.bot===true||(p.connected!==false&&now-p.lastSeen<ONLINE_MS));}
export function slowFactor(p,now){return now<(p.slowedUntil||0)?(p.slowMultiplier??.5):1;}
export function allOnline(s,now){const joined=s.players.filter(Boolean);return joined.length>=2&&joined.every(p=>online(p,now));}
export function blocked(x,y){return HOUSES.some(h=>x>h.x-17&&x<h.x+217&&y>h.y-17&&y<h.y+207);}
export function proximity(p,i){const h=HOUSES[i];return Math.hypot(p.x-h.x-100,p.y-h.y-227)<61;}
function series(s){return s.series??={round:1,wins:[0,0,0,0],complete:false,champions:[]};}
export function reset(s,keepSeries=false){if(!keepSeries)s.series={round:1,wins:[0,0,0,0],complete:false,champions:[]};s.phase='waiting';s.winner=null;s.marks=[[],[],[],[]];s.shieldUntil=[0,0,0,0];s.events=[];s.lastBotTick=null;s.players.forEach((p,i)=>{if(p){p.ready=!!p.bot;delete p.botRoute;delete p.botTarget;delete p.botCleanAt;delete p.points;p.x=350+i*34;p.y=885;p.lastFart=0;p.lastClean=0;p.slowedUntil=0;p.slowMultiplier=1;p.hitImmuneUntil=0;p.chargeStarted=null;p.cleanChargeStarted=null;p.cleanReadyAt=0;p.fartReadyAt=0;}});}
function movementBudget(p,now){const start=Math.max(p.lastMove,now-2400),cuts=[start,now];for(const t of [p.slowedUntil,p.chargeStarted])if(Number.isFinite(t)&&t>start&&t<now)cuts.push(t);cuts.sort((a,b)=>a-b);let distance=14;for(let i=1;i<cuts.length;i++){const mid=(cuts[i]+cuts[i-1])/2;distance+=253*(slowFactor(p,mid))*(p.chargeStarted!=null&&mid>=p.chargeStarted?.65:1)*(cuts[i]-cuts[i-1])/1000;}return Math.min(distance,550);}
export function movePlayer(p,pos,now,allowed){if(!allowed||!pos||!Number.isFinite(pos.x)||!Number.isFinite(pos.y))return;p.lastMove??=now;const dx=pos.x-p.x,dy=pos.y-p.y,d=Math.hypot(dx,dy),max=movementBudget(p,now),ratio=d>max?max/d:1,n=Math.max(1,Math.ceil(d*ratio/10));for(let i=0;i<n;i++){let x=Math.max(25,Math.min(775,p.x+dx*ratio/n)),y=Math.max(25,Math.min(955,p.y+dy*ratio/n));if(!blocked(x,p.y))p.x=x;if(!blocked(p.x,y))p.y=y;}p.lastMove=now;}
export function tick(s,slot,input,now){const p=s.players[slot];p.lastSeen=now;if(!allOnline(s,now))s.players.forEach(other=>{if(other){other.chargeStarted=null;other.cleanChargeStarted=null;}});movePlayer(p,input.position,now,s.phase==='playing'&&allOnline(s,now));if(p.cleanChargeStarted!=null&&!proximity(p,slot))p.cleanChargeStarted=null;if(s.phase==='waiting'&&typeof input.ready==='boolean')p.ready=input.ready;if(s.phase==='waiting'&&s.autofill){const humans=s.players.filter(p=>p&&!p.bot);if(humans.length&&humans.every(p=>online(p,now)&&p.ready))fillBots(s,now);}if(s.phase==='waiting'&&allOnline(s,now)&&s.players.filter(Boolean).every(p=>p.ready)){s.phase='playing';s.startedAt=now;s.events.push({id:++s.seq,kind:'start',at:now});s.players.forEach(p=>{if(p)p.lastMove=now;});} }
function event(s,e,now){s.events.push({...e,id:++s.seq,at:now});s.events=s.events.filter(e=>now-e.at<12000).slice(-40);}
function checkVictory(s,slot,now){if(s.marks[slot].length===0&&s.marks.every((m,i)=>i===slot||m.includes(slot))){s.phase='finished';s.winner=slot;const set=series(s);set.wins[slot]++;set.complete=set.wins[slot]>=3||set.round>=5;if(set.complete){const best=Math.max(...set.wins);set.champions=set.wins.flatMap((wins,i)=>s.players[i]&&wins===best?[i]:[]);}s.players.forEach(p=>{if(p){p.chargeStarted=null;p.cleanChargeStarted=null;}});event(s,{kind:'win',actor:slot},now);}}
export function act(s,slot,kind,now){const p=s.players[slot];if(kind==='rematch'){if(s.phase!=='finished')throw Error('Finish this match first.');const set=series(s);if(set.complete)reset(s);else{set.round++;reset(s,true);}return;}if(s.phase!=='playing')throw Error('The match is not playing.');if(!allOnline(s,now))throw Error('Waiting for all joined players to reconnect.');if(kind==='charge'){if(p.cleanChargeStarted!=null)throw Error('Finish cleansing first.');if(now<(p.fartReadyAt??p.lastFart+1000))throw Error('Fart recharging.');p.chargeStarted??=now;return;}if(kind==='cancelCharge'){p.chargeStarted=null;return;}if(kind==='fart'){const mega=p.chargeStarted!=null&&now-p.chargeStarted>=1000;p.chargeStarted=null;if(now<(p.fartReadyAt??p.lastFart+1000))throw Error('Fart recharging.');p.lastFart=now;p.fartReadyAt=now+(mega?2500:1000);const victims=[];s.players.forEach((other,i)=>{if(other&&i!==slot&&Math.hypot(p.x-other.x,p.y-other.y)<(mega?115:65)){victims.push(i);if(now>=(other.hitImmuneUntil||0)){other.slowedUntil=now+(mega?3000:1000);other.slowMultiplier=mega?.5:.75;other.hitImmuneUntil=now+2500;}}});let house=null;for(let i=0;i<4;i++)if(now>=(s.shieldUntil?.[i]||0)&&(mega?Math.hypot(p.x-HOUSES[i].x-100,p.y-HOUSES[i].y-227)<105:proximity(p,i))){if(!s.marks[i].includes(slot))s.marks[i].push(slot);house=i;}event(s,{kind:'fart',actor:slot,x:p.x,y:p.y,victims,house,mega},now);checkVictory(s,slot,now);return;}if(kind==='cancelCleanCharge'){p.cleanChargeStarted=null;return;}if(kind==='chargeClean'){if(!proximity(p,slot))throw Error('Return to your own front door to cleanse.');if(now<(p.cleanReadyAt??p.lastClean+2000))throw Error('Cleanser recharging.');if(p.chargeStarted!=null)throw Error('Finish your fart first.');p.cleanChargeStarted??=now;return;}if(kind==='clean'){const mega=p.cleanChargeStarted!=null&&now-p.cleanChargeStarted>=1000;p.cleanChargeStarted=null;if(!proximity(p,slot))throw Error('Return to your own front door to cleanse.');if(now<(p.cleanReadyAt??p.lastClean+2000))throw Error('Cleanser recharging.');p.lastClean=now;p.cleanReadyAt=now+(mega?6000:2000);s.marks[slot]=[];s.shieldUntil??=[0,0,0,0];if(mega)s.shieldUntil[slot]=now+2000;event(s,{kind:'clean',actor:slot,house:slot,x:HOUSES[slot].x+100,y:HOUSES[slot].y+227,mega},now);checkVictory(s,slot,now);return;}throw Error('Unknown action.');}
export function publicState(s,now,revision=0){return{revision,serverTime:now,series:series(s),autofill:!!s.autofill,hostSlot:s.hostSlot??s.players.findIndex(p=>p&&!p.bot),removable:s.players.flatMap((p,i)=>p&&!online(p,now)&&now-(p.disconnectedAt??p.lastSeen+ONLINE_MS)>=10000?[i]:[]),code:s.code,phase:s.phase,winner:s.winner,marks:s.marks,shieldUntil:s.shieldUntil||[0,0,0,0],events:s.events,paused:s.phase==='playing'&&!allOnline(s,now),players:s.players.map((p,i)=>p?{slot:i,bot:!!p.bot,name:p.name||NAMES[i],x:p.x,y:p.y,ready:p.ready,slowedUntil:p.slowedUntil||0,slowMultiplier:p.slowMultiplier??.5,chargeStarted:p.chargeStarted??null,cleanChargeStarted:p.cleanChargeStarted??null,cleanReadyAt:p.cleanReadyAt??p.lastClean+2000,fartReadyAt:p.fartReadyAt??p.lastFart+1000,online:online(p,now),progress:s.marks.filter((m,house)=>house!==i&&m.includes(i)).length,homeClean:s.marks[i].length===0}:null)};}


// Bots use the same authoritative movement, cooldown, tag and victory rules as people.
export function fillBots(s,now){for(let slot=0;slot<4;slot++)if(!s.players[slot])s.players[slot]={bot:true,token:null,device:null,name:['Pink Bot','Cyan Bot','Gold Bot','Purple Bot'][slot],x:350+slot*34,y:885,ready:true,lastSeen:now,lastMove:now,lastFart:0,lastClean:0,slowedUntil:0,chargeStarted:null,fartReadyAt:0};s.lastBotTick=now;}
export function stepBots(s,now){const dt=Math.min(.25,Math.max(0,(now-(s.lastBotTick??now))/1000));s.lastBotTick=now;if(s.phase!=='playing'||!allOnline(s,now)||!dt)return false;let changed=false;
for(let slot=0;slot<4&&s.phase==='playing';slot++){const p=s.players[slot];if(!p?.bot)continue;p.lastSeen=now;changed=true;
const remaining=[1,2,3].map(offset=>(slot+offset)%4).filter(i=>!s.marks[i].includes(slot));
if(p.cleanChargeStarted!=null){if(!proximity(p,slot))act(s,slot,'cancelCleanCharge',now);else if(now-p.cleanChargeStarted>=1050)act(s,slot,'clean',now);continue;}
if(p.chargeStarted!=null){if(now-p.chargeStarted>=1050)act(s,slot,'fart',now);continue;}
const needClean=s.marks[slot].length&&(!remaining.length||now>=(p.botCleanAt||0));
const target=needClean||!remaining.length?slot:remaining.includes(p.botTarget)?p.botTarget:remaining[0],door={x:HOUSES[target].x+100,y:HOUSES[target].y+227};
if(target===slot&&proximity(p,slot)){if(now>=(p.cleanReadyAt??p.lastClean+2000)){act(s,slot,slot%2===0?'chargeClean':'clean',now);p.botCleanAt=now+6000+slot*500;delete p.botTarget;delete p.botRoute;}continue;}
if(p.botTarget!==target||!p.botRoute?.length){p.botTarget=target;p.botRoute=[{x:400,y:p.y},{x:400,y:door.y},door];}
if(Math.hypot(p.x-door.x,p.y-door.y)<45){if(now>=p.fartReadyAt){if(slot%2===0)act(s,slot,'charge',now);else act(s,slot,'fart',now);}continue;}
const next=p.botRoute[0],dx=next.x-p.x,dy=next.y-p.y,d=Math.hypot(dx,dy),distance=Math.min(d,(160+slot*6)*dt*(slowFactor(p,now)));
if(d<3){p.botRoute.shift();continue;}
movePlayer(p,{x:p.x+dx/d*distance,y:p.y+dy/d*distance},now,true);
if(now>=p.fartReadyAt&&s.players.some((other,i)=>other&&i!==slot&&Math.hypot(p.x-other.x,p.y-other.y)<55))act(s,slot,'fart',now);
}return changed;}
